---
seed:           10
device:         cuda:3


# mesh, time
finemeshsize:   257
coarsemeshsize: 33
timesteps:      100
length:         3.2
dt:             0.01
datatimestart:  0
iter:           2


# parameters
parahigh:       0.07
paralow:        0.02
num_para:       6
repeat:         36


# data
datafile:       /home/xinyang/storage/projects/PDE_structure/2Dburgers/known/burgers_new.pt

# network
network:        cnn2dRich


# training
epochs:         500
batchsize:      800
lr:             1.e-3
noiseinject:    False


# add pde?
pde:            True


# path
tensorboarddir: /home/xinyang/storage/projects/PDE_structure/2Dburgers/new/PDE_iter3
modelsavepath:  /home/xinyang/storage/projects/PDE_structure/2Dburgers/new/model_PDE_iter3.pth

# equation
rhsu:           burgers2Dpu
rhsv:           burgers2Dpv
...