---
seed:           10
device:         cuda:0


# mesh, time
finemeshsize:   257
coarsemeshsize: 49
timesteps:      100
length:         3.2
dt:             0.02
datatimestart:  0



# parameters
parahigh:       0.07
paralow:        0.02
num_para:       6
repeat:         36


# data
datafile:       /home/xinyang/storage/projects/PDE_structure/2Dburgers/burgers_new.pt

# network
network:        SimpleViT


# training
epochs:         1500
batchsize:      800
lr:             1.e-4
noiseinject:    False


# add pde?
pde:            False


# path
tensorboarddir: /storage/xinyang/projects/PDE_structure/2DburgersViT/noPDE
modelsavepath:  /storage/xinyang/projects/PDE_structure/2DburgersViT/model_noPDE.pth

...