---
seed:           10
device:         cuda:0


# mesh, time
finemeshsize:   257
coarsemeshsize: 49
timesteps:      16
length:         3.2
dt:             0.002
datatimestart:  0



# parameters
parahigh:       0.09
paralow:        0.02
num_para:       1
repeat:         256


# data
datafile:       convection_2D.pth

# network
network:        cnn2dnop


# training
epochs:         3200
batchsize:      800
lr:             1.e-3
noiseinject:    False


# add pde?
pde:            True


# path
tensorboarddir: /home/xinyang/store/dynamic/PDE_structure/2D/transfer/pretrain/convcPDE
modelsavepath:  model_convc_PDE.pth


# equation
rhsu:           convecu
rhsv:           convecv
...