---
seed:           10
device:         cuda:1


# mesh, time
finemeshsize:   257
coarsemeshsize: 49
timesteps:      16
length:         3.2
dt:             0.002
datatimestart:  0



# parameters
parahigh:       0.09
paralow:        0.02
num_para:       8
repeat:         32


# data
datafile:       diffusion_2D_p.pth

# network
network:        cnn2d


# training
epochs:         3200
batchsize:      800
lr:             1.e-3
noiseinject:    False


# add pde?
pde:            True


# path
tensorboarddir: /home/xinyang/store/dynamic/PDE_structure/2D/transfer/pretrain/diffPDE
modelsavepath:  model_diff_PDE.pth


# equation
rhsu:           diffu
rhsv:           diffv
...