---
seed:           10
device:         cuda:0


# mesh, time
finemeshsize:   129
coarsemeshsize: 17
timesteps:      100
length:         25.132741229 # 8\pi
dt:             0.05
datatimestart:  200



# parameters
parahigh:       0.8
paralow:        0.2
num_para:       1
repeat:         256


# data
datafile:       KS_1Dl.pth

# network
network:        mlpnop
hidden_size:    48
hidden_layers:  3


# training
epochs:         4400
batchsize:      128
lr:             5.e-3
noiseinject:    False


# add pde?
pde:            True


# path
tensorboarddir: /home/lxy/store/projects/dynamic/PDE_structure/1D/KS/unkonwn1/PDE3
modelsavepath:  model_ks_un_PDEl3.pth


# equation
rhs:           ks1d
...