---
seed:           10
device:         cuda:0


# mesh, time
finemeshsize:   [100,400]
coarsemeshsize: [25,100]
timesteps:      73
datatimestart:  1.6
dt:             0.8


# parameters
para1low:       0.3
para1high:      0.7
para2low:       2000
para2high:      10000
num_para1:      9
num_para2:      5     

# data
fdata:         /home/xinyang/storage/projects/PDE_structure/NS/magnetic3/pipefine.pt
cdata:         /home/xinyang/storage/projects/PDE_structure/NS/magnetic3/pipecoarse.pt

# network
network:        cnn2dNSRich


# training
epochs:         3200
batchsize:      256
lr:             1.e-3
noiseinject:    False


# add pde?
pde:            True


# path
tensorboarddir: /home/xinyang/storage/projects/PDE_structure/NS/magnetic3/fPDE
modelsavepath:  /home/xinyang/storage/projects/PDE_structure/NS/magnetic3/model_fPDE.pth
template:       /home/xinyang/storage/projects/PDE_structure/NS/magnetic3/templatef
tmp:            /home/xinyang/storage/projects/PDE_structure/NS/magnetic3/tmpf

solver:         /home/xinyang/OpenFOAM/xinyang-8/applications/solvers/incompressible/myicoFoam/myicoFoam

...
