---
seed:           10
device:         cuda:0


# mesh, time
finemeshsize:   [100,400]
coarsemeshsize: [25,100]
timesteps:      56
datatimestart:  15.2
dt:             0.8


# parameters
para1low:       0.3
para1high:      0.7
para2low:       2000
para2high:      10000
num_para1:      9
num_para2:      5     

# data
fdata:         /home/xinyang/storage/projects/PDE_structure/NS/pipefine.pt
cdata:         /home/xinyang/storage/projects/PDE_structure/NS/pipecoarsep.pt

# network
network:        cnn2dNSRich


# training
epochs:         3200
batchsize:      256
lr:             1.e-3
noiseinject:    False


# add pde?
pde:            True


# path
tensorboarddir: /home/xinyang/storage/projects/PDE_structure/NS/pPDE
modelsavepath:  /home/xinyang/storage/projects/PDE_structure/NS/pPDE.pth
template:       /home/xinyang/storage/projects/PDE_structure/NS/templatep
tmp:            /home/xinyang/storage/projects/PDE_structure/NS/tmpp

solver:         icoFoam

...
