---
seed:           10
device:         cuda:0


# mesh, time
finemeshsize:   [100,400]
coarsemeshsize: [25,100]
timesteps:      73
datatimestart:  1.6
dt:             0.8


# parameters
para1low:       0.3
para1high:      0.7
para2low:       2000
para2high:      10000
num_para1:      9
num_para2:      5     

# data
fdata:         /home/xinyang/storage/projects/PDE_structure/NS/origin/pipefine_origin_long.pt
cdata:         /home/xinyang/storage/projects/PDE_structure/NS/origin/pipecoarse.pt

# network
network:        cnn2dNSRich
inchannels:     10


# training
epochs:         3200
batchsize:      256
lr:             1.e-3
noiseinject:    False


# add pde?
pde:            True


# path
tensorboarddir: /home/xinyang/storage/projects/PDE_structure/NS/origin/PDEe
modelsavepath:  /home/xinyang/storage/projects/PDE_structure/NS/origin/model_pPDEe.pth
template:       /home/xinyang/storage/projects/PDE_structure/NS/origin/template
tmp:            /home/xinyang/storage/projects/PDE_structure/NS/origin/tmpe

solver:         icoFoam

...
