---
seed:           10
device:         cuda:0


# mesh, time
finemeshsize:   400
coarsemeshsize: 100
timesteps:      85
datatimestart:  0
dt:             0.001


# parameters
paralow:        0.0
parahigh:       0.0
num_para:       85
repeat:         1

# data
fudata:         /home/lxy/remote_storage/projects/PDE_preserved/OpenFoam/velocity.pth
fpdata:         /home/lxy/remote_storage/projects/PDE_preserved/OpenFoam/pressure.pth
cudata:         /home/lxy/remote_storage/projects/PDE_preserved/OpenFoam/velocityc.pth
cpdata:         /home/lxy/remote_storage/projects/PDE_preserved/OpenFoam/pressurec.pth

# network
network:        cnn2dns


# training
epochs:         3200
batchsize:      40
lr:             1.e-3
noiseinject:    False


# add pde?
pde:            True


# path
tensorboarddir: /home/lxy/store/projects/dynamic/PDE_structure/OpenFoam/test1/tb
modelsavepath:  model_ns_PDE.pth
template:       /home/lxy/store/projects/dynamic/PDE_structure/OpenFoam/coarse_temp
tmp:            /home/lxy/store/projects/dynamic/PDE_structure/OpenFoam/tmp

...