---
seed:           10
device:         cuda:0


# mesh, time
finemeshsize:   [100,400]
coarsemeshsize: [25,100]
timesteps:      80
datatimestart:  70
dt:             0.2


# parameters
para1low:       0.3
para1high:      0.7
para2low:       2000
para2high:      10000
num_para1:      9
num_para2:      5     

# data
fdata:         /home/xinyang/storage/projects/PDE_structure/OpenFoam/pipeflow.pt
cdata:         /home/xinyang/storage/projects/PDE_structure/OpenFoam/pipeflow_c.pt

# network
network:        cnn2dns


# training
epochs:         3200
batchsize:      512
lr:             1.e-3
noiseinject:    False


# add pde?
pde:            True


# path
tensorboarddir: /home/xinyang/storage/projects/PDE_structure/OpenFoam/pipe/PDE
modelsavepath:  model_pipe_PDE.pth
template:       /home/xinyang/storage/projects/PDE_structure/OpenFoam/pipe/template
tmp:            /home/xinyang/storage/projects/PDE_structure/OpenFoam/pipe/tmp

...