---
seed:           10
device:         cuda:1


# mesh, time
finemeshsize:   257
coarsemeshsize: 49
timesteps:      100
length:         6.4
dt:             0.002
datatimestart:  10



# parameters
parahigh:       1.3
paralow:        0.2
num_para:       12
repeat:         16


# data
datafile:       /home/xinyang/storage/projects/PDE_structure/RD/RD_new.pt

# network
network:        cnn2d


# training
epochs:         1000
batchsize:      800
lr:             1.e-3
noiseinject:    False


# add pde?
pde:            False


# path
tensorboarddir: /home/xinyang/storage/projects/PDE_structure/RD/new/noPDE
modelsavepath:  /home/xinyang/storage/projects/PDE_structure/RD/new/model_noPDE.pth


# equation
rhsu:           rd0u
rhsv:           rd0v
...