---
seed:           10
device:         cuda:0


# mesh, time
finemeshsize:   257
coarsemeshsize: 49
timesteps:      50
length:         6.4
dt:             0.002
datatimestart:  10



# parameters
parahigh:       0.8
paralow:        0.2
num_para:       8
repeat:         16


# data
datafile:       /home/xinyang/storage/projects/PDE_structure/RD/RD.pt

# network
network:        cnn2dRich


# training
epochs:         1000
batchsize:      800
lr:             1.e-3
noiseinject:    False


# add pde?
pde:            True


# path
tensorboarddir: /home/xinyang/storage/projects/PDE_structure/RD/pPDE
modelsavepath:  /home/xinyang/storage/projects/PDE_structure/RD/model_pPDE.pth

# equation
rhsu:           rdpu
rhsv:           rdpv
...