---
seed:           10
device:         cuda:2


# mesh, time
finemeshsize:   257
coarsemeshsize: 49
timesteps:      16
length:         3.2
dt:             0.002
datatimestart:  0



# parameters
parahigh:       0.09
paralow:        0.02
num_para:       8
repeat:         2


# data
datafile:       burgers_2D_transfer.pth

# network
network:        cnn2d


# training
epochs:         1200
batchsize:      800
lr:             1.e-3
noiseinject:    False


# add pde?
pde:            True


# path
tensorboarddir: /home/xinyang/store/dynamic/PDE_structure/2D/transfer/burgers_un_PDE_less
modelsavepath:  model_transfer_PDE_less.pth


# equation
rhsu:           burgers2Du
rhsv:           burgers2Dv

# pretrain models
rhsu0:          diffu
rhsv0:          diffv
rhsu1:          convecu
rhsv1:          convecv
prenet0:        cnn2d
prenet1:        cnn2dnop
prenetfile0:    model_diff_PDE.pth
prenetfile1:    model_convc_PDE.pth
predata0:       diffusion_2D_p.pth
predata1:       convection_2D.pth

...